### ISSUE TITLE
crash on avvir.xml, no parent node (Bugzilla Bug 2069)

### ISSUE THREAD

**Issue by albbas** [divvun/CorpusTools#214]
This issue was created automatically with bugzilla2github
# Bugzilla Bug 2069
Date: 2015-07-07T13:33:55+02:00
From: @unhammer (Originally created by @unhammer)
To:   @albbas
CC:   @ciprian-NO, @snomos, @Trondtr

Last updated: 2015-07-09T19:51:12+02:00

**Comment by albbas** [comment]
## Comment 10562
Date: 2015-07-07 13:33:55 +0200
From: @unhammer

in boundcorpus, I get:

$ convert2xml --serial orig/sme/news/avvir/avvir_xml-filer/avvir_2013_xml-filer/11nr000av_surran.article.xml
Collecting files to convert
Starting the conversion of 1 files
converting orig/sme/news/avvir/avvir_xml-filer/avvir_2013_xml-filer/11nr000av_surran.article.xml
Traceback (most recent call last):
  File "/Users/unhammer/virt_env/ct-svn/bin/convert2xml", line 9, in <module>
    load_entry_point('CorpusTools==0.9.0b4', 'console_scripts', 'convert2xml')()
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 2585, in main
    cm.convert_serially()
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 2509, in convert_serially
    self.convert(xsl_file)
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 2444, in convert
    conv.write_complete(self.LANGUAGEGUESSER)
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 259, in write_complete
    complete = self.make_complete(languageguesser)
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 243, in make_complete
    complete = self.transform_to_complete()
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 140, in transform_to_complete
    intermediate = self.convert2intermediate()
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 382, in convert2intermediate
    self.convert_p()
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 417, in convert_p
    self.convert_subelement(p)
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 408, in convert_subelement
    i = self.insert_element(p, subelement.tail, i)
  File "/Users/unhammer/virt_env/ct-svn/lib/python2.7/site-packages/CorpusTools-0.9.0b4-py2.7.egg/corpustools/converter.py", line 393, in insert_element
    grandparent.insert(grandparent.index(p) + i, new_p)
AttributeError: 'NoneType' object has no attribute 'insert'


Is the purpose of convert_subelement to flatten the nodes?

**Comment by albbas** [comment]
## Comment 10565
Date: 2015-07-08 18:38:34 +0200
From: @albbas

convert_subelement is used to make a new p out of each tag out of inside a p element.

The old avvir documents had span and br elements inside the p elements (as illustrated in setUp in TestAvvirConverter), the newer documents have p elements inside p elements which makes the conversion fall flat on the face.

**Comment by albbas** [comment]
## Comment 10567
Date: 2015-07-08 18:57:54 +0200
From: @albbas

Here is an example paragraph:

<p class="NormalParagraphStyle"/>Muitalan ahte dán jagi ge lea<p class="tekst">Dán jagi muitala maid iežas</p> gártan fitnat muorra­meah­c<p class="tekst">c</p>is. – Dán jagi lean ferten finadit muorrameahc<p class="tekst">c</p>is, nu ahte dál lea šiljus muorra­guorbmi. Muorra­meahcci lea juoga<p class="tekst">idá</p> maid vuoruhan dárbbu mielde, go de lea nohkkon muor<p class="tekst">r</p>as, lohká son. Muđuid lohká iežas snihkkegoahtán garáša<p class="tekst"> álggán snihkket biillastálla,</p> masa maid manná olu<p class="tekst">lo</p> áigi.<p class="tekst"><br/> – </p> </p>

**Comment by albbas** [comment]
## Comment 10568
Date: 2015-07-09 19:51:12 +0200
From: @albbas

This is solved in CorpusTools 0.9.3
